language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "svstoll-github"
    token:
      secure: "IC4SrBcf/8ePr8rfWwTFvVA5rYN+9ahMJU1VjEysxyFNoJh06O2D9LGxmvmoACZXuvTYtv71hFUwiVSHwNLmnw9QhZH07hcWDS9sURN0k+QsnvZPu0ONfttZy6ITnJsnXJuBg1M/VWKeoecgSgbNe3868QgLC7aQKK8IAl23SDzvGIGQAlsVSyq1FjV5Zaym532lI02J5TlAWdBt7uXPxlnOrIIhDlciUplt6Q7X/YGhzJI3KEn4KoTHN8psZkrnWoqEIUNXFMr4e0fxDmwdfYrfME8/spaFm4jS4yKBTpZy259zNIVtJ0Xs0lCRDQNQQxRhrabsXCrQhPSiaSFGU5uvJUwPTjJ2ScuYdfmqb3J0GU96ys2SNWGadgkPfNMZc8GVB7cliHaEtT7vukCaFfk4bC9ZYykuEwgW2sFNeOixTY+7mPJZM2Xf6FjyCgmt4HlbvmGrLRvCgTT9rV9GGAjYYHBhXGopxt7xkERsZ373ZEW4paQI0B44D9GbzGs368m2O/NDwwmspUudWOvU0F/qqG/nGD40jf2Dg0EDUTfYbqeHroHPFInKVE+E6n0hmBQC1rq578qIYb1/jTVX1MbAGBVCbwf2tD/+2LQNg0t0oQC6PSWG9p8zB2sk+g/20nbFKKRVjOBgs8Vd+lvSV/rV8518fa7JjG22vn9ieZM="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - bash <(curl -s https://codecov.io/bash)